name: socialworkprotal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  #webview_flutter: ^4.2.1
  modal_progress_hud_nsn: ^0.3.0
  loading_animation_widget: ^1.2.0+4
  flutter_easyloading: ^3.0.5
  flutter_inappwebview: ^5.7.2+3
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  awesome_notifications: ^0.7.4+1
  open_filex: ^4.3.2

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

